name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER_NAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "."
        target: "/mySrc"

